/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminRepairView {
  'id' : OrderId,
  'status' : RepairStatus,
  'devicePhotoFileIds' : Array<FileId>,
  'client' : Client,
  'additionalDescription' : string,
  'deliveredAt' : [] | [Timestamp],
  'balance' : bigint,
  'code' : RepairCode,
  'createdAt' : Timestamp,
  'intakeDate' : Timestamp,
  'reportedIssue' : string,
  'hasDniPhoto' : boolean,
  'estimatedDeliveryDate' : [] | [Timestamp],
  'damagePhotoFileIds' : Array<FileId>,
  'deposit' : bigint,
  'diagnosis' : string,
  'device' : Device,
  'updatedAt' : Timestamp,
  'totalPrice' : bigint,
  'estimatedTime' : string,
  'observations' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Client {
  'id' : OrderId,
  'dni' : string,
  'createdAt' : Timestamp,
  'fullName' : string,
  'email' : [] | [string],
  'phone' : Phone,
}
export interface Device {
  'id' : OrderId,
  'model' : string,
  'imei' : [] | [string],
  'physicalCondition' : string,
  'brand' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FileId = string;
export interface IntakeInput {
  'dni' : string,
  'devicePhotoFileIds' : Array<FileId>,
  'model' : string,
  'imei' : [] | [string],
  'reportedIssue' : string,
  'fullName' : string,
  'deposit' : bigint,
  'email' : [] | [string],
  'dniPhotoFileId' : [] | [FileId],
  'physicalCondition' : string,
  'brand' : string,
  'phone' : Phone,
  'totalPrice' : bigint,
}
export type LookupResult = { 'found' : PublicRepairView } |
  { 'notFound' : null };
export type OrderId = bigint;
export type Phone = string;
export interface PublicRepairView {
  'status' : RepairStatus,
  'devicePhotoFileIds' : Array<FileId>,
  'model' : string,
  'balance' : bigint,
  'code' : RepairCode,
  'intakeDate' : Timestamp,
  'reportedIssue' : string,
  'estimatedDeliveryDate' : [] | [Timestamp],
  'fullName' : string,
  'damagePhotoFileIds' : Array<FileId>,
  'deposit' : bigint,
  'diagnosis' : string,
  'brand' : string,
  'totalPrice' : bigint,
  'estimatedTime' : string,
  'observations' : string,
}
export type RepairCode = string;
export interface RepairOrderUpdate {
  'estimatedDeliveryDate' : [] | [Timestamp],
  'deposit' : [] | [bigint],
  'diagnosis' : [] | [string],
  'totalPrice' : [] | [bigint],
  'estimatedTime' : [] | [string],
  'observations' : [] | [string],
}
export interface RepairRequestInput {
  'additionalDescription' : string,
  'model' : string,
  'reportedIssue' : string,
  'fullName' : string,
  'damagePhotoFileIds' : Array<FileId>,
  'email' : [] | [string],
  'brand' : string,
  'phone' : Phone,
}
export type RepairStatus = { 'Recibido' : null } |
  { 'Entregado' : null } |
  { 'EnReparacion' : null } |
  { 'Probando' : null } |
  { 'ListoParaEntregar' : null } |
  { 'Diagnosticando' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type StatusChangeResult = {
    'ok' : { 'order' : AdminRepairView, 'notificationSent' : boolean }
  } |
  { 'notFound' : null };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Attach additional photos to an order. Admin only.
   */
  'addOrderPhotos' : ActorMethod<
    [OrderId, Array<FileId>, Array<FileId>],
    AdminRepairView
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Change the status of an order. When `notify` is true, sends an email to the
   * / client with the repair code and the new status. Admin only.
   */
  'changeRepairStatus' : ActorMethod<
    [OrderId, RepairStatus, boolean],
    StatusChangeResult
  >,
  /**
   * / Create a repair order from an admin intake (reception) form. Admin only.
   */
  'createRepairOrder' : ActorMethod<[IntakeInput], AdminRepairView>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of the public backend API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Retrieve the PRIVATE DNI photo file id for an order. Admin only; never
   * / exposed through any public/customer endpoint.
   */
  'getDniPhoto' : ActorMethod<[OrderId], [] | [FileId]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List all completed (delivered) orders. Admin only.
   */
  'listCompletedRepairs' : ActorMethod<[], Array<AdminRepairView>>,
  /**
   * / List all orders still in progress (not yet delivered). Admin only.
   */
  'listPendingRepairs' : ActorMethod<[], Array<AdminRepairView>>,
  /**
   * / Look up a single repair by code and/or phone. Returns only that order's
   * / public fields; never exposes the DNI photo or other customers' orders.
   * / When both a code and a phone are supplied, the order must match BOTH:
   * / a valid code with a mismatched phone yields #notFound.
   */
  'lookupRepair' : ActorMethod<[[] | [RepairCode], [] | [Phone]], LookupResult>,
  /**
   * / Register a new client. Admin only.
   */
  'registerClient' : ActorMethod<[string, Phone, string], Client>,
  /**
   * / Register a new device. Admin only.
   */
  'registerDevice' : ActorMethod<
    [string, string, [] | [string], string],
    Device
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search orders by name, phone, code or model. Admin only.
   */
  'searchRepairs' : ActorMethod<[string], Array<AdminRepairView>>,
  /**
   * / Submit a repair request from the customer app. Creates the client (if new),
   * / the device, and the order, and returns the generated repair code.
   */
  'submitRepairRequest' : ActorMethod<[RepairRequestInput], RepairCode>,
  /**
   * / Update an existing order's diagnosis, price, deposit, estimate, delivery
   * / date and observations. Balance is recomputed automatically. Admin only.
   */
  'updateRepairOrder' : ActorMethod<
    [OrderId, RepairOrderUpdate],
    AdminRepairView
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];