/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const OrderId = IDL.Nat;
export const FileId = IDL.Text;
export const RepairStatus = IDL.Variant({
  'Recibido' : IDL.Null,
  'Entregado' : IDL.Null,
  'EnReparacion' : IDL.Null,
  'Probando' : IDL.Null,
  'ListoParaEntregar' : IDL.Null,
  'Diagnosticando' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Phone = IDL.Text;
export const Client = IDL.Record({
  'id' : OrderId,
  'dni' : IDL.Text,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : Phone,
});
export const RepairCode = IDL.Text;
export const Device = IDL.Record({
  'id' : OrderId,
  'model' : IDL.Text,
  'imei' : IDL.Opt(IDL.Text),
  'physicalCondition' : IDL.Text,
  'brand' : IDL.Text,
});
export const AdminRepairView = IDL.Record({
  'id' : OrderId,
  'status' : RepairStatus,
  'devicePhotoFileIds' : IDL.Vec(FileId),
  'client' : Client,
  'additionalDescription' : IDL.Text,
  'deliveredAt' : IDL.Opt(Timestamp),
  'balance' : IDL.Nat,
  'code' : RepairCode,
  'createdAt' : Timestamp,
  'intakeDate' : Timestamp,
  'reportedIssue' : IDL.Text,
  'hasDniPhoto' : IDL.Bool,
  'estimatedDeliveryDate' : IDL.Opt(Timestamp),
  'damagePhotoFileIds' : IDL.Vec(FileId),
  'deposit' : IDL.Nat,
  'diagnosis' : IDL.Text,
  'device' : Device,
  'updatedAt' : Timestamp,
  'totalPrice' : IDL.Nat,
  'estimatedTime' : IDL.Text,
  'observations' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StatusChangeResult = IDL.Variant({
  'ok' : IDL.Record({
    'order' : AdminRepairView,
    'notificationSent' : IDL.Bool,
  }),
  'notFound' : IDL.Null,
});
export const IntakeInput = IDL.Record({
  'dni' : IDL.Text,
  'devicePhotoFileIds' : IDL.Vec(FileId),
  'model' : IDL.Text,
  'imei' : IDL.Opt(IDL.Text),
  'reportedIssue' : IDL.Text,
  'fullName' : IDL.Text,
  'deposit' : IDL.Nat,
  'email' : IDL.Opt(IDL.Text),
  'dniPhotoFileId' : IDL.Opt(FileId),
  'physicalCondition' : IDL.Text,
  'brand' : IDL.Text,
  'phone' : Phone,
  'totalPrice' : IDL.Nat,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const PublicRepairView = IDL.Record({
  'status' : RepairStatus,
  'devicePhotoFileIds' : IDL.Vec(FileId),
  'model' : IDL.Text,
  'balance' : IDL.Nat,
  'code' : RepairCode,
  'intakeDate' : Timestamp,
  'reportedIssue' : IDL.Text,
  'estimatedDeliveryDate' : IDL.Opt(Timestamp),
  'fullName' : IDL.Text,
  'damagePhotoFileIds' : IDL.Vec(FileId),
  'deposit' : IDL.Nat,
  'diagnosis' : IDL.Text,
  'brand' : IDL.Text,
  'totalPrice' : IDL.Nat,
  'estimatedTime' : IDL.Text,
  'observations' : IDL.Text,
});
export const LookupResult = IDL.Variant({
  'found' : PublicRepairView,
  'notFound' : IDL.Null,
});
export const RepairRequestInput = IDL.Record({
  'additionalDescription' : IDL.Text,
  'model' : IDL.Text,
  'reportedIssue' : IDL.Text,
  'fullName' : IDL.Text,
  'damagePhotoFileIds' : IDL.Vec(FileId),
  'email' : IDL.Opt(IDL.Text),
  'brand' : IDL.Text,
  'phone' : Phone,
});
export const RepairOrderUpdate = IDL.Record({
  'estimatedDeliveryDate' : IDL.Opt(Timestamp),
  'deposit' : IDL.Opt(IDL.Nat),
  'diagnosis' : IDL.Opt(IDL.Text),
  'totalPrice' : IDL.Opt(IDL.Nat),
  'estimatedTime' : IDL.Opt(IDL.Text),
  'observations' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addOrderPhotos' : IDL.Func(
      [OrderId, IDL.Vec(FileId), IDL.Vec(FileId)],
      [AdminRepairView],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeRepairStatus' : IDL.Func(
      [OrderId, RepairStatus, IDL.Bool],
      [StatusChangeResult],
      [],
    ),
  'createRepairOrder' : IDL.Func([IntakeInput], [AdminRepairView], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDniPhoto' : IDL.Func([OrderId], [IDL.Opt(FileId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCompletedRepairs' : IDL.Func([], [IDL.Vec(AdminRepairView)], ['query']),
  'listPendingRepairs' : IDL.Func([], [IDL.Vec(AdminRepairView)], ['query']),
  'lookupRepair' : IDL.Func(
      [IDL.Opt(RepairCode), IDL.Opt(Phone)],
      [LookupResult],
      ['query'],
    ),
  'registerClient' : IDL.Func([IDL.Text, Phone, IDL.Text], [Client], []),
  'registerDevice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [Device],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchRepairs' : IDL.Func([IDL.Text], [IDL.Vec(AdminRepairView)], ['query']),
  'submitRepairRequest' : IDL.Func([RepairRequestInput], [RepairCode], []),
  'updateRepairOrder' : IDL.Func(
      [OrderId, RepairOrderUpdate],
      [AdminRepairView],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const OrderId = IDL.Nat;
  const FileId = IDL.Text;
  const RepairStatus = IDL.Variant({
    'Recibido' : IDL.Null,
    'Entregado' : IDL.Null,
    'EnReparacion' : IDL.Null,
    'Probando' : IDL.Null,
    'ListoParaEntregar' : IDL.Null,
    'Diagnosticando' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Phone = IDL.Text;
  const Client = IDL.Record({
    'id' : OrderId,
    'dni' : IDL.Text,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : Phone,
  });
  const RepairCode = IDL.Text;
  const Device = IDL.Record({
    'id' : OrderId,
    'model' : IDL.Text,
    'imei' : IDL.Opt(IDL.Text),
    'physicalCondition' : IDL.Text,
    'brand' : IDL.Text,
  });
  const AdminRepairView = IDL.Record({
    'id' : OrderId,
    'status' : RepairStatus,
    'devicePhotoFileIds' : IDL.Vec(FileId),
    'client' : Client,
    'additionalDescription' : IDL.Text,
    'deliveredAt' : IDL.Opt(Timestamp),
    'balance' : IDL.Nat,
    'code' : RepairCode,
    'createdAt' : Timestamp,
    'intakeDate' : Timestamp,
    'reportedIssue' : IDL.Text,
    'hasDniPhoto' : IDL.Bool,
    'estimatedDeliveryDate' : IDL.Opt(Timestamp),
    'damagePhotoFileIds' : IDL.Vec(FileId),
    'deposit' : IDL.Nat,
    'diagnosis' : IDL.Text,
    'device' : Device,
    'updatedAt' : Timestamp,
    'totalPrice' : IDL.Nat,
    'estimatedTime' : IDL.Text,
    'observations' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StatusChangeResult = IDL.Variant({
    'ok' : IDL.Record({
      'order' : AdminRepairView,
      'notificationSent' : IDL.Bool,
    }),
    'notFound' : IDL.Null,
  });
  const IntakeInput = IDL.Record({
    'dni' : IDL.Text,
    'devicePhotoFileIds' : IDL.Vec(FileId),
    'model' : IDL.Text,
    'imei' : IDL.Opt(IDL.Text),
    'reportedIssue' : IDL.Text,
    'fullName' : IDL.Text,
    'deposit' : IDL.Nat,
    'email' : IDL.Opt(IDL.Text),
    'dniPhotoFileId' : IDL.Opt(FileId),
    'physicalCondition' : IDL.Text,
    'brand' : IDL.Text,
    'phone' : Phone,
    'totalPrice' : IDL.Nat,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const PublicRepairView = IDL.Record({
    'status' : RepairStatus,
    'devicePhotoFileIds' : IDL.Vec(FileId),
    'model' : IDL.Text,
    'balance' : IDL.Nat,
    'code' : RepairCode,
    'intakeDate' : Timestamp,
    'reportedIssue' : IDL.Text,
    'estimatedDeliveryDate' : IDL.Opt(Timestamp),
    'fullName' : IDL.Text,
    'damagePhotoFileIds' : IDL.Vec(FileId),
    'deposit' : IDL.Nat,
    'diagnosis' : IDL.Text,
    'brand' : IDL.Text,
    'totalPrice' : IDL.Nat,
    'estimatedTime' : IDL.Text,
    'observations' : IDL.Text,
  });
  const LookupResult = IDL.Variant({
    'found' : PublicRepairView,
    'notFound' : IDL.Null,
  });
  const RepairRequestInput = IDL.Record({
    'additionalDescription' : IDL.Text,
    'model' : IDL.Text,
    'reportedIssue' : IDL.Text,
    'fullName' : IDL.Text,
    'damagePhotoFileIds' : IDL.Vec(FileId),
    'email' : IDL.Opt(IDL.Text),
    'brand' : IDL.Text,
    'phone' : Phone,
  });
  const RepairOrderUpdate = IDL.Record({
    'estimatedDeliveryDate' : IDL.Opt(Timestamp),
    'deposit' : IDL.Opt(IDL.Nat),
    'diagnosis' : IDL.Opt(IDL.Text),
    'totalPrice' : IDL.Opt(IDL.Nat),
    'estimatedTime' : IDL.Opt(IDL.Text),
    'observations' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addOrderPhotos' : IDL.Func(
        [OrderId, IDL.Vec(FileId), IDL.Vec(FileId)],
        [AdminRepairView],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeRepairStatus' : IDL.Func(
        [OrderId, RepairStatus, IDL.Bool],
        [StatusChangeResult],
        [],
      ),
    'createRepairOrder' : IDL.Func([IntakeInput], [AdminRepairView], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDniPhoto' : IDL.Func([OrderId], [IDL.Opt(FileId)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCompletedRepairs' : IDL.Func(
        [],
        [IDL.Vec(AdminRepairView)],
        ['query'],
      ),
    'listPendingRepairs' : IDL.Func([], [IDL.Vec(AdminRepairView)], ['query']),
    'lookupRepair' : IDL.Func(
        [IDL.Opt(RepairCode), IDL.Opt(Phone)],
        [LookupResult],
        ['query'],
      ),
    'registerClient' : IDL.Func([IDL.Text, Phone, IDL.Text], [Client], []),
    'registerDevice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [Device],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchRepairs' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdminRepairView)],
        ['query'],
      ),
    'submitRepairRequest' : IDL.Func([RepairRequestInput], [RepairCode], []),
    'updateRepairOrder' : IDL.Func(
        [OrderId, RepairOrderUpdate],
        [AdminRepairView],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };