/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AdminRepairView {
    id: OrderId;
    status: RepairStatus;
    devicePhotoFileIds: Array<FileId>;
    client: Client;
    additionalDescription: string;
    deliveredAt?: Timestamp;
    balance: bigint;
    code: RepairCode;
    createdAt: Timestamp;
    intakeDate: Timestamp;
    reportedIssue: string;
    hasDniPhoto: boolean;
    estimatedDeliveryDate?: Timestamp;
    damagePhotoFileIds: Array<FileId>;
    deposit: bigint;
    diagnosis: string;
    device: Device;
    updatedAt: Timestamp;
    totalPrice: bigint;
    estimatedTime: string;
    observations: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Client {
    id: OrderId;
    dni: string;
    createdAt: Timestamp;
    fullName: string;
    email?: string;
    phone: Phone;
}
export interface Device {
    id: OrderId;
    model: string;
    imei?: string;
    physicalCondition: string;
    brand: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type FileId = string;
export interface IntakeInput {
    dni: string;
    devicePhotoFileIds: Array<FileId>;
    model: string;
    imei?: string;
    reportedIssue: string;
    fullName: string;
    deposit: bigint;
    email?: string;
    dniPhotoFileId?: FileId;
    physicalCondition: string;
    brand: string;
    phone: Phone;
    totalPrice: bigint;
}
export type LookupResult = {
    __kind__: "found";
    found: PublicRepairView;
} | {
    __kind__: "notFound";
    notFound: null;
};
export type OrderId = bigint;
export type Phone = string;
export interface PublicRepairView {
    status: RepairStatus;
    devicePhotoFileIds: Array<FileId>;
    model: string;
    balance: bigint;
    code: RepairCode;
    intakeDate: Timestamp;
    reportedIssue: string;
    estimatedDeliveryDate?: Timestamp;
    fullName: string;
    damagePhotoFileIds: Array<FileId>;
    deposit: bigint;
    diagnosis: string;
    brand: string;
    totalPrice: bigint;
    estimatedTime: string;
    observations: string;
}
export type RepairCode = string;
export interface RepairOrderUpdate {
    estimatedDeliveryDate?: Timestamp;
    deposit?: bigint;
    diagnosis?: string;
    totalPrice?: bigint;
    estimatedTime?: string;
    observations?: string;
}
export interface RepairRequestInput {
    additionalDescription: string;
    model: string;
    reportedIssue: string;
    fullName: string;
    damagePhotoFileIds: Array<FileId>;
    email?: string;
    brand: string;
    phone: Phone;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type StatusChangeResult = {
    __kind__: "ok";
    ok: {
        order: AdminRepairView;
        notificationSent: boolean;
    };
} | {
    __kind__: "notFound";
    notFound: null;
};
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum RepairStatus {
    Recibido = "Recibido",
    Entregado = "Entregado",
    EnReparacion = "EnReparacion",
    Probando = "Probando",
    ListoParaEntregar = "ListoParaEntregar",
    Diagnosticando = "Diagnosticando"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Attach additional photos to an order. Admin only.
     */
    addOrderPhotos(id: OrderId, damagePhotoFileIds: Array<FileId>, devicePhotoFileIds: Array<FileId>): Promise<AdminRepairView>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Change the status of an order. When `notify` is true, sends an email to the
     * / client with the repair code and the new status. Admin only.
     */
    changeRepairStatus(id: OrderId, status: RepairStatus, notify: boolean): Promise<StatusChangeResult>;
    /**
     * / Create a repair order from an admin intake (reception) form. Admin only.
     */
    createRepairOrder(input: IntakeInput): Promise<AdminRepairView>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Static Markdown documentation of the public backend API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Retrieve the PRIVATE DNI photo file id for an order. Admin only; never
     * / exposed through any public/customer endpoint.
     */
    getDniPhoto(id: OrderId): Promise<FileId | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List all completed (delivered) orders. Admin only.
     */
    listCompletedRepairs(): Promise<Array<AdminRepairView>>;
    /**
     * / List all orders still in progress (not yet delivered). Admin only.
     */
    listPendingRepairs(): Promise<Array<AdminRepairView>>;
    /**
     * / Look up a single repair by code and/or phone. Returns only that order's
     * / public fields; never exposes the DNI photo or other customers' orders.
     * / When both a code and a phone are supplied, the order must match BOTH:
     * / a valid code with a mismatched phone yields #notFound.
     */
    lookupRepair(code: RepairCode | null, phone: Phone | null): Promise<LookupResult>;
    /**
     * / Register a new client. Admin only.
     */
    registerClient(fullName: string, phone: Phone, dni: string): Promise<Client>;
    /**
     * / Register a new device. Admin only.
     */
    registerDevice(brand: string, model: string, imei: string | null, physicalCondition: string): Promise<Device>;
    schema(): Promise<string>;
    /**
     * / Search orders by name, phone, code or model. Admin only.
     */
    searchRepairs(term: string): Promise<Array<AdminRepairView>>;
    /**
     * / Submit a repair request from the customer app. Creates the client (if new),
     * / the device, and the order, and returns the generated repair code.
     */
    submitRepairRequest(input: RepairRequestInput): Promise<RepairCode>;
    /**
     * / Update an existing order's diagnosis, price, deposit, estimate, delivery
     * / date and observations. Balance is recomputed automatically. Admin only.
     */
    updateRepairOrder(id: OrderId, update: RepairOrderUpdate): Promise<AdminRepairView>;
}
import type { AdminRepairView as _AdminRepairView, Cell as _Cell, Client as _Client, Device as _Device, Error as _Error, FileId as _FileId, IntakeInput as _IntakeInput, LookupResult as _LookupResult, OrderId as _OrderId, Phone as _Phone, PublicRepairView as _PublicRepairView, RepairCode as _RepairCode, RepairOrderUpdate as _RepairOrderUpdate, RepairRequestInput as _RepairRequestInput, RepairStatus as _RepairStatus, Result as _Result, Result__1 as _Result__1, StatusChangeResult as _StatusChangeResult, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addOrderPhotos(arg0: OrderId, arg1: Array<FileId>, arg2: Array<FileId>): Promise<AdminRepairView> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrderPhotos(arg0, arg1, arg2);
                return from_candid_AdminRepairView_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrderPhotos(arg0, arg1, arg2);
            return from_candid_AdminRepairView_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeRepairStatus(arg0: OrderId, arg1: RepairStatus, arg2: boolean): Promise<StatusChangeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.changeRepairStatus(arg0, to_candid_RepairStatus_n15(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_StatusChangeResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeRepairStatus(arg0, to_candid_RepairStatus_n15(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_StatusChangeResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRepairOrder(arg0: IntakeInput): Promise<AdminRepairView> {
        if (this.processError) {
            try {
                const result = await this.actor.createRepairOrder(to_candid_IntakeInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AdminRepairView_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRepairOrder(to_candid_IntakeInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AdminRepairView_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDniPhoto(arg0: OrderId): Promise<FileId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDniPhoto(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDniPhoto(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCompletedRepairs(): Promise<Array<AdminRepairView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCompletedRepairs();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCompletedRepairs();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingRepairs(): Promise<Array<AdminRepairView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingRepairs();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingRepairs();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async lookupRepair(arg0: RepairCode | null, arg1: Phone | null): Promise<LookupResult> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupRepair(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_LookupResult_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupRepair(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_LookupResult_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerClient(arg0: string, arg1: Phone, arg2: string): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.registerClient(arg0, arg1, arg2);
                return from_candid_Client_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerClient(arg0, arg1, arg2);
            return from_candid_Client_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerDevice(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<Device> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDevice(arg0, arg1, to_candid_opt_n38(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Device_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDevice(arg0, arg1, to_candid_opt_n38(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Device_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchRepairs(arg0: string): Promise<Array<AdminRepairView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRepairs(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRepairs(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRepairRequest(arg0: RepairRequestInput): Promise<RepairCode> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRepairRequest(to_candid_RepairRequestInput_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRepairRequest(to_candid_RepairRequestInput_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRepairOrder(arg0: OrderId, arg1: RepairOrderUpdate): Promise<AdminRepairView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRepairOrder(arg0, to_candid_RepairOrderUpdate_n41(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AdminRepairView_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRepairOrder(arg0, to_candid_RepairOrderUpdate_n41(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AdminRepairView_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminRepairView_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminRepairView): AdminRepairView {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Device_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Device): Device {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_LookupResult_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LookupResult): LookupResult {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PublicRepairView_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicRepairView): PublicRepairView {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RepairStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairStatus): RepairStatus {
    return "Recibido" in value ? RepairStatus.Recibido : "Entregado" in value ? RepairStatus.Entregado : "EnReparacion" in value ? RepairStatus.EnReparacion : "Probando" in value ? RepairStatus.Probando : "ListoParaEntregar" in value ? RepairStatus.ListoParaEntregar : "Diagnosticando" in value ? RepairStatus.Diagnosticando : value;
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StatusChangeResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusChangeResult): StatusChangeResult {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileId]): FileId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    model: string;
    imei: [] | [string];
    physicalCondition: string;
    brand: string;
}): {
    id: OrderId;
    model: string;
    imei?: string;
    physicalCondition: string;
    brand: string;
} {
    return {
        id: value.id,
        model: value.model,
        imei: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.imei)),
        physicalCondition: value.physicalCondition,
        brand: value.brand
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    order: _AdminRepairView;
    notificationSent: boolean;
}): {
    order: AdminRepairView;
    notificationSent: boolean;
} {
    return {
        order: from_candid_AdminRepairView_n5(_uploadFile, _downloadFile, value.order),
        notificationSent: value.notificationSent
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n23(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n27(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RepairStatus;
    devicePhotoFileIds: Array<_FileId>;
    model: string;
    balance: bigint;
    code: _RepairCode;
    intakeDate: _Timestamp;
    reportedIssue: string;
    estimatedDeliveryDate: [] | [_Timestamp];
    fullName: string;
    damagePhotoFileIds: Array<_FileId>;
    deposit: bigint;
    diagnosis: string;
    brand: string;
    totalPrice: bigint;
    estimatedTime: string;
    observations: string;
}): {
    status: RepairStatus;
    devicePhotoFileIds: Array<FileId>;
    model: string;
    balance: bigint;
    code: RepairCode;
    intakeDate: Timestamp;
    reportedIssue: string;
    estimatedDeliveryDate?: Timestamp;
    fullName: string;
    damagePhotoFileIds: Array<FileId>;
    deposit: bigint;
    diagnosis: string;
    brand: string;
    totalPrice: bigint;
    estimatedTime: string;
    observations: string;
} {
    return {
        status: from_candid_RepairStatus_n7(_uploadFile, _downloadFile, value.status),
        devicePhotoFileIds: value.devicePhotoFileIds,
        model: value.model,
        balance: value.balance,
        code: value.code,
        intakeDate: value.intakeDate,
        reportedIssue: value.reportedIssue,
        estimatedDeliveryDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.estimatedDeliveryDate)),
        fullName: value.fullName,
        damagePhotoFileIds: value.damagePhotoFileIds,
        deposit: value.deposit,
        diagnosis: value.diagnosis,
        brand: value.brand,
        totalPrice: value.totalPrice,
        estimatedTime: value.estimatedTime,
        observations: value.observations
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _RepairStatus;
    devicePhotoFileIds: Array<_FileId>;
    client: _Client;
    additionalDescription: string;
    deliveredAt: [] | [_Timestamp];
    balance: bigint;
    code: _RepairCode;
    createdAt: _Timestamp;
    intakeDate: _Timestamp;
    reportedIssue: string;
    hasDniPhoto: boolean;
    estimatedDeliveryDate: [] | [_Timestamp];
    damagePhotoFileIds: Array<_FileId>;
    deposit: bigint;
    diagnosis: string;
    device: _Device;
    updatedAt: _Timestamp;
    totalPrice: bigint;
    estimatedTime: string;
    observations: string;
}): {
    id: OrderId;
    status: RepairStatus;
    devicePhotoFileIds: Array<FileId>;
    client: Client;
    additionalDescription: string;
    deliveredAt?: Timestamp;
    balance: bigint;
    code: RepairCode;
    createdAt: Timestamp;
    intakeDate: Timestamp;
    reportedIssue: string;
    hasDniPhoto: boolean;
    estimatedDeliveryDate?: Timestamp;
    damagePhotoFileIds: Array<FileId>;
    deposit: bigint;
    diagnosis: string;
    device: Device;
    updatedAt: Timestamp;
    totalPrice: bigint;
    estimatedTime: string;
    observations: string;
} {
    return {
        id: value.id,
        status: from_candid_RepairStatus_n7(_uploadFile, _downloadFile, value.status),
        devicePhotoFileIds: value.devicePhotoFileIds,
        client: from_candid_Client_n8(_uploadFile, _downloadFile, value.client),
        additionalDescription: value.additionalDescription,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.deliveredAt)),
        balance: value.balance,
        code: value.code,
        createdAt: value.createdAt,
        intakeDate: value.intakeDate,
        reportedIssue: value.reportedIssue,
        hasDniPhoto: value.hasDniPhoto,
        estimatedDeliveryDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.estimatedDeliveryDate)),
        damagePhotoFileIds: value.damagePhotoFileIds,
        deposit: value.deposit,
        diagnosis: value.diagnosis,
        device: from_candid_Device_n12(_uploadFile, _downloadFile, value.device),
        updatedAt: value.updatedAt,
        totalPrice: value.totalPrice,
        estimatedTime: value.estimatedTime,
        observations: value.observations
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    dni: string;
    createdAt: _Timestamp;
    fullName: string;
    email: [] | [string];
    phone: _Phone;
}): {
    id: OrderId;
    dni: string;
    createdAt: Timestamp;
    fullName: string;
    email?: string;
    phone: Phone;
} {
    return {
        id: value.id,
        dni: value.dni,
        createdAt: value.createdAt,
        fullName: value.fullName,
        email: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.email)),
        phone: value.phone
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        order: _AdminRepairView;
        notificationSent: boolean;
    };
} | {
    notFound: null;
}): {
    __kind__: "ok";
    ok: {
        order: AdminRepairView;
        notificationSent: boolean;
    };
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n18(_uploadFile, _downloadFile, value.ok)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    found: _PublicRepairView;
} | {
    notFound: null;
}): {
    __kind__: "found";
    found: PublicRepairView;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "found" in value ? {
        __kind__: "found",
        found: from_candid_PublicRepairView_n36(_uploadFile, _downloadFile, value.found)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminRepairView>): Array<AdminRepairView> {
    return value.map((x)=>from_candid_AdminRepairView_n5(_uploadFile, _downloadFile, x));
}
function to_candid_IntakeInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntakeInput): _IntakeInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_RepairOrderUpdate_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairOrderUpdate): _RepairOrderUpdate {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_RepairRequestInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairRequestInput): _RepairRequestInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_RepairStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairStatus): _RepairStatus {
    return value == RepairStatus.Recibido ? {
        Recibido: null
    } : value == RepairStatus.Entregado ? {
        Entregado: null
    } : value == RepairStatus.EnReparacion ? {
        EnReparacion: null
    } : value == RepairStatus.Probando ? {
        Probando: null
    } : value == RepairStatus.ListoParaEntregar ? {
        ListoParaEntregar: null
    } : value == RepairStatus.Diagnosticando ? {
        Diagnosticando: null
    } : value;
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RepairCode | null): [] | [_RepairCode] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Phone | null): [] | [_Phone] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dni: string;
    devicePhotoFileIds: Array<FileId>;
    model: string;
    imei?: string;
    reportedIssue: string;
    fullName: string;
    deposit: bigint;
    email?: string;
    dniPhotoFileId?: FileId;
    physicalCondition: string;
    brand: string;
    phone: Phone;
    totalPrice: bigint;
}): {
    dni: string;
    devicePhotoFileIds: Array<_FileId>;
    model: string;
    imei: [] | [string];
    reportedIssue: string;
    fullName: string;
    deposit: bigint;
    email: [] | [string];
    dniPhotoFileId: [] | [_FileId];
    physicalCondition: string;
    brand: string;
    phone: _Phone;
    totalPrice: bigint;
} {
    return {
        dni: value.dni,
        devicePhotoFileIds: value.devicePhotoFileIds,
        model: value.model,
        imei: value.imei ? candid_some(value.imei) : candid_none(),
        reportedIssue: value.reportedIssue,
        fullName: value.fullName,
        deposit: value.deposit,
        email: value.email ? candid_some(value.email) : candid_none(),
        dniPhotoFileId: value.dniPhotoFileId ? candid_some(value.dniPhotoFileId) : candid_none(),
        physicalCondition: value.physicalCondition,
        brand: value.brand,
        phone: value.phone,
        totalPrice: value.totalPrice
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    additionalDescription: string;
    model: string;
    reportedIssue: string;
    fullName: string;
    damagePhotoFileIds: Array<FileId>;
    email?: string;
    brand: string;
    phone: Phone;
}): {
    additionalDescription: string;
    model: string;
    reportedIssue: string;
    fullName: string;
    damagePhotoFileIds: Array<_FileId>;
    email: [] | [string];
    brand: string;
    phone: _Phone;
} {
    return {
        additionalDescription: value.additionalDescription,
        model: value.model,
        reportedIssue: value.reportedIssue,
        fullName: value.fullName,
        damagePhotoFileIds: value.damagePhotoFileIds,
        email: value.email ? candid_some(value.email) : candid_none(),
        brand: value.brand,
        phone: value.phone
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    estimatedDeliveryDate?: Timestamp;
    deposit?: bigint;
    diagnosis?: string;
    totalPrice?: bigint;
    estimatedTime?: string;
    observations?: string;
}): {
    estimatedDeliveryDate: [] | [_Timestamp];
    deposit: [] | [bigint];
    diagnosis: [] | [string];
    totalPrice: [] | [bigint];
    estimatedTime: [] | [string];
    observations: [] | [string];
} {
    return {
        estimatedDeliveryDate: value.estimatedDeliveryDate ? candid_some(value.estimatedDeliveryDate) : candid_none(),
        deposit: value.deposit ? candid_some(value.deposit) : candid_none(),
        diagnosis: value.diagnosis ? candid_some(value.diagnosis) : candid_none(),
        totalPrice: value.totalPrice ? candid_some(value.totalPrice) : candid_none(),
        estimatedTime: value.estimatedTime ? candid_some(value.estimatedTime) : candid_none(),
        observations: value.observations ? candid_some(value.observations) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
